package dev.paperplane.cli.testing

import org.objectweb.asm.ClassWriter
import org.objectweb.asm.MethodVisitor
import org.objectweb.asm.Opcodes

/**
 * ASM-generated bytecode fixtures for instant-tier classifier tests — the CLI-side sibling of the
 * `generateClass` helper in the companion's `ClassChangeDetectorTest`. Synthesizing real `.class`
 * bytes (rather than compiling sources) keeps each test's structural delta explicit: a test that
 * adds an annotated method literally adds one [MethodSpec] with one annotation descriptor.
 */
object BytecodeFixtures {

  class MethodSpec(
      val name: String,
      val desc: String = "()V",
      val access: Int = Opcodes.ACC_PUBLIC,
      val annotations: List<String> = emptyList(),
      val exceptions: Array<String>? = null,
      val body: (MethodVisitor) -> Unit = { it.visitInsn(Opcodes.RETURN) },
  )

  fun generateClass(
      name: String = "com/example/Test",
      access: Int = Opcodes.ACC_PUBLIC,
      superName: String = "java/lang/Object",
      interfaces: Array<String>? = null,
      classAnnotations: List<String> = emptyList(),
      fields: List<Triple<Int, String, String>> = emptyList(),
      methods: List<MethodSpec> = emptyList(),
      innerClassName: String? = null,
  ): ByteArray {
    val cw = ClassWriter(0)
    cw.visit(Opcodes.V21, access, name, null, superName, interfaces)
    for (desc in classAnnotations) {
      cw.visitAnnotation(desc, true).visitEnd()
    }
    if (innerClassName != null) {
      cw.visitInnerClass(innerClassName, name, innerClassName.substringAfterLast('$'), 0)
    }
    for ((fieldAccess, fieldName, fieldDesc) in fields) {
      cw.visitField(fieldAccess, fieldName, fieldDesc, null, null).visitEnd()
    }
    for (spec in methods) {
      val mv = cw.visitMethod(spec.access, spec.name, spec.desc, null, spec.exceptions)
      for (desc in spec.annotations) {
        mv.visitAnnotation(desc, true).visitEnd()
      }
      mv.visitCode()
      spec.body(mv)
      mv.visitMaxs(4, 4)
      mv.visitEnd()
    }
    cw.visitEnd()
    return cw.toByteArray()
  }

  /** A method body that pushes and pops [value] before returning — distinct per value. */
  fun bodyReturning(value: Int): (MethodVisitor) -> Unit = { mv ->
    mv.visitLdcInsn(value)
    mv.visitInsn(Opcodes.POP)
    mv.visitInsn(Opcodes.RETURN)
  }

  /** A body identical in instructions to the default but carrying a line-number debug entry. */
  fun bodyWithLineNumber(line: Int): (MethodVisitor) -> Unit = { mv ->
    val label = org.objectweb.asm.Label()
    mv.visitLabel(label)
    mv.visitLineNumber(line, label)
    mv.visitInsn(Opcodes.RETURN)
  }

  /** Writes [bytes] as `<dir>/<fqcn-as-path>.class`, creating parent directories. */
  fun writeClassFile(dir: java.io.File, fqcn: String, bytes: ByteArray): java.io.File =
      java.io.File(dir, fqcn.replace('.', '/') + ".class").apply {
        parentFile.mkdirs()
        writeBytes(bytes)
      }
}
