package dev.paperplane.cli.plugins

import com.charleskorn.kaml.Yaml
import com.charleskorn.kaml.YamlConfiguration
import java.io.File
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString

/**
 * The on-disk schema for `paperplane-lock.yml`. A frozen snapshot of resolved versions, filenames,
 * URLs, and SHA256 hashes — like `package-lock.json` or `Cargo.lock`. Committed to source control
 * so teammates get byte-identical plugin sets without hitting the Modrinth API.
 *
 * `version: 1` is a schema version, bumped if we ever need a breaking format change. It's separate
 * from the plugin version numbers themselves.
 */
@Serializable
data class PluginLockfile(
    val version: Int = 1,
    val plugins: List<LockedPlugin> = emptyList(),
) {
  /**
   * Looks up an entry by slug, case-insensitively. Slugs are normalized to lowercase at
   * construction time in the resolver, but hand-edited lockfiles may still contain mixed casing —
   * this method handles both cases so `find("WorldEdit")` matches a stored `"worldedit"` and vice
   * versa.
   */
  fun find(slug: String): LockedPlugin? = plugins.firstOrNull {
    it.slug.equals(slug, ignoreCase = true)
  }

  /**
   * Returns a copy with [entry] added or replaced (matched case-insensitively by slug), with the
   * list re-sorted alphabetically so single-plugin updates produce minimal lockfile diffs.
   */
  fun upsert(entry: LockedPlugin): PluginLockfile {
    val remaining = plugins.filterNot { it.slug.equals(entry.slug, ignoreCase = true) }
    return copy(plugins = (remaining + entry).sortedBy { it.slug.lowercase() })
  }

  fun remove(slug: String): PluginLockfile =
      copy(plugins = plugins.filterNot { it.slug.equals(slug, ignoreCase = true) })

  companion object {
    private const val HEADER_COMMENT =
        "# Auto-generated by ppl. Do not edit — use `ppl plugin add/remove/update` instead.\n"

    private val yaml =
        Yaml(configuration = YamlConfiguration(encodeDefaults = true, breakScalarsAt = 160))

    fun load(projectDir: File): PluginLockfile {
      val file = File(projectDir, "paperplane-lock.yml")
      if (!file.exists()) return PluginLockfile()
      val text = file.readText()
      // Strip leading comment lines so kaml doesn't trip on the header.
      val yamlBody =
          text.lineSequence().dropWhile { it.startsWith("#") || it.isBlank() }.joinToString("\n")
      if (yamlBody.isBlank()) return PluginLockfile()
      return yaml.decodeFromString(yamlBody)
    }

    fun save(projectDir: File, lockfile: PluginLockfile) {
      val file = File(projectDir, "paperplane-lock.yml")
      val body = yaml.encodeToString(lockfile)
      file.writeText(HEADER_COMMENT + body)
    }

    /** Delete the lockfile. Idempotent. */
    fun delete(projectDir: File) {
      File(projectDir, "paperplane-lock.yml").delete()
    }
  }
}

/**
 * One frozen plugin entry. For `modrinth` source: all fields populated, plus [url] for re-download
 * from cache-miss. For `local` source: [url] and [filename] still populated (filename = basename of
 * the local path), but [url] is left empty because there's nothing to download.
 */
@Serializable
data class LockedPlugin(
    val slug: String,
    val source: String, // "modrinth" or "local"
    val version: String,
    val sha512: String,
    val url: String = "",
    val filename: String,
    /**
     * Whether the entry in `paperplane.yml` pinned a specific version (e.g. `vault@1.7.3`). Pinned
     * entries are not touched by `ppl plugin update` without `--force`.
     */
    val pinned: Boolean = false,
)
