package dev.paperplane.companion

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.objectweb.asm.ClassReader
import org.objectweb.asm.ClassWriter
import org.objectweb.asm.Opcodes

class AsmShadingTest {

    @Test
    fun `ClassReader can be instantiated from JDK class`() {
        val reader = ClassReader("java.lang.Object")
        assertNotNull(reader)
        assertEquals("java/lang/Object", reader.className)
    }

    @Test
    fun `ClassWriter can generate bytecode`() {
        val cw = ClassWriter(0)
        cw.visit(Opcodes.V21, Opcodes.ACC_PUBLIC, "com/example/Generated", null, "java/lang/Object", null)
        cw.visitEnd()
        val bytes = cw.toByteArray()

        assertNotNull(bytes)
        assertTrue(bytes.size > 0)
    }

    @Test
    fun `generated bytecode is valid and round-trips through ClassReader`() {
        val cw = ClassWriter(0)
        cw.visit(Opcodes.V21, Opcodes.ACC_PUBLIC, "com/example/RoundTrip", null, "java/lang/Object", null)

        cw.visitField(Opcodes.ACC_PRIVATE, "value", "I", null, null)

        val mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "getValue", "()I", null, null)
        mv.visitCode()
        mv.visitVarInsn(Opcodes.ALOAD, 0)
        mv.visitFieldInsn(Opcodes.GETFIELD, "com/example/RoundTrip", "value", "I")
        mv.visitInsn(Opcodes.IRETURN)
        mv.visitMaxs(1, 1)
        mv.visitEnd()

        cw.visitEnd()
        val bytes = cw.toByteArray()

        // Read it back
        val reader = ClassReader(bytes)
        assertEquals("com/example/RoundTrip", reader.className)
        assertEquals("java/lang/Object", reader.superName)
    }
}
