package dev.paperplane.companion

import org.objectweb.asm.ClassWriter
import org.objectweb.asm.Opcodes

/**
 * ASM-generated bytecode fixtures for companion tests — real, definable `.class` bytes without
 * compiling sources, so each test controls exactly what the loader or swapper sees.
 */
object BytecodeFixtures {

  /** A minimal `public class <internalName> {}` with just the default constructor. */
  fun emptyClass(internalName: String): ByteArray = build(internalName) {}

  /** [emptyClass] plus `public static int getValue()` returning [value]. */
  fun classWithStaticValue(internalName: String, value: Int): ByteArray =
      build(internalName) { cw ->
        val mv =
            cw.visitMethod(Opcodes.ACC_PUBLIC or Opcodes.ACC_STATIC, "getValue", "()I", null, null)
        mv.visitCode()
        mv.visitLdcInsn(value)
        mv.visitInsn(Opcodes.IRETURN)
        mv.visitMaxs(1, 0)
        mv.visitEnd()
      }

  /**
   * [emptyClass] plus `public int marker()` returning [marker] — byte-distinct per marker, for
   * tests that need distinguishable "versions" of the same class (CRC verification ladders).
   */
  fun classWithMarker(internalName: String, marker: Int): ByteArray =
      build(internalName) { cw ->
        val mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "marker", "()I", null, null)
        mv.visitCode()
        mv.visitLdcInsn(marker)
        mv.visitInsn(Opcodes.IRETURN)
        mv.visitMaxs(2, 1)
        mv.visitEnd()
      }

  private fun build(internalName: String, members: (ClassWriter) -> Unit): ByteArray {
    val cw = ClassWriter(0)
    cw.visit(Opcodes.V21, Opcodes.ACC_PUBLIC, internalName, null, "java/lang/Object", null)
    val init = cw.visitMethod(Opcodes.ACC_PUBLIC, "<init>", "()V", null, null)
    init.visitCode()
    init.visitVarInsn(Opcodes.ALOAD, 0)
    init.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false)
    init.visitInsn(Opcodes.RETURN)
    init.visitMaxs(1, 1)
    init.visitEnd()
    members(cw)
    cw.visitEnd()
    return cw.toByteArray()
  }
}
